connections :
  databases :
    sinauto_mcma_ :
        server: "PC\\SQLEXPRESS"          
        driver: "ODBC Driver 17 for SQL Server"
    SinAuto_MCMA_retour :
        server: "PC\\SQLEXPRESS"          
        driver: "ODBC Driver 17 for SQL Server"
    

    


# connections :

#   databases :

#     mamda_app :
#         server: "PC\\SQLEXPRESS"          
#         driver: "ODBC Driver 17 for SQL Server"
#         schemas : 
#             - acctra
#             - rd
#         # auth :
#         #     uid : "${user_name}"
#         #     pwd : "${password}"     

#     mcma_app :
#         server: "PC\\SQLEXPRESS"
#         driver: "ODBC Driver 17 for SQL Server"
#         schemas : 
#             - acctra
#             - rd
#         # trusted_connection: "yes" 
#         # auth :
#         #     uid : "${username}"
#         #     pwd : "${password}"      

#     mamda_auto :
#         server: "PC\\SQLEXPRESS"
#         driver: "ODBC Driver 17 for SQL Server"
#         schemas : 
#             - ''
#         # trusted_connection: "yes"
#         # auth :
#         #     uid : "${username}"
#         #     pwd : "${password}"        

#     mcma_auto :
#         server: "PC\\SQLEXPRESS"
#         driver: "ODBC Driver 17 for SQL Server"
#         schemas: 
#             - ""
#         # trusted_connection: "yes" 
#         # auth :
#         #     uid : "${username}"
#         #     pwd : "${password}"     