connections :

    databases :

      MAMDA_APP :
        - server: "PC\\SQLEXPRESS"
        - database: "MAMDA_App"
        - driver: "ODBC Driver 17 for SQL Server"
        - trusted_connection: "yes"      

      MCMA_APP :
        - server: "PC\\SQLEXPRESS"
        - database: "MCMA_App"
        - driver: "ODBC Driver 17 for SQL Server"
        - trusted_connection: "yes"  

      MCMA_AUTO :
        - server: "PC\\SQLEXPRESS"
        - database: "MCMA_Auto"
        - driver: "ODBC Driver 17 for SQL Server"
        - trusted_connection: "yes"   

      MAMDA_AUTO :
        - server: "PC\\SQLEXPRESS"
        - database: "MCMA_Auto"
        - driver: "ODBC Driver 17 for SQL Server"
        - trusted_connection: "yes"       
      
