connections :

  databases :

    mamda_app :
        server: "PC\\SQLEXPRESS"          
        driver: "ODBC Driver 17 for SQL Server"
        trusted_connection: "yes"      

    mcma_app :
        server: "PC\\SQLEXPRESS"
        driver: "ODBC Driver 17 for SQL Server"
        trusted_connection: "yes"  

    mamda_auto :
        server: "PC\\SQLEXPRESS"
        driver: "ODBC Driver 17 for SQL Server"
        trusted_connection: "yes"   

    mcma_auto :
        server: "PC\\SQLEXPRESS"
        driver: "ODBC Driver 17 for SQL Server"
        trusted_connection: "yes" 
