connections :

  databases :

    mamda_app :
        server: "PC\\SQLEXPRESS"          
        driver: "ODBC Driver 17 for SQL Server"
        schemas : 
            - acctra
            - rd
        # auth :
        #     uid : "${user_name}"
        #     pwd : "${password}"     

    mcma_app :
        server: "PC\\SQLEXPRESS"
        driver: "ODBC Driver 17 for SQL Server"
        schemas : 
            - acctra
            - rd
        # trusted_connection: "yes" 
        # auth :
        #     uid : "${username}"
        #     pwd : "${password}"      

    mamda_auto :
        server: "PC\\SQLEXPRESS"
        driver: "ODBC Driver 17 for SQL Server"
        # trusted_connection: "yes"
        # auth :
        #     uid : "${username}"
        #     pwd : "${password}"        

    mcma_auto :
        server: "PC\\SQLEXPRESS"
        driver: "ODBC Driver 17 for SQL Server"
        # trusted_connection: "yes" 
        # auth :
        #     uid : "${username}"
        #     pwd : "${password}"     