table_mapping: 
  num_donneur: 'num_donneur_ordre'
  reference_remise: 'reference_remise'
  code_banque_receptrice: 'code_banque_receptrice'
  date_emission: 'date_emission'
  num_remise: 'num_remise'
  ref_ben: 'ref_beneficiaire'
  montant: 'montant'
  date_execution: 'date_execution'
  nom_donneur: 'nom_donneur_ordre'
  nom_beneficiaire: 'nom_benificiaire'
  rib_donneur: 'rib_donneur_ordre'
  rib_beneficiaire: 'rib_beneficiaire'
  motif_virement: 'motif_virement'
  reference_virement: 'reference_virement'
  reference_ben: 'reference_beneficiaire'
  montant_total: 'montant_total'
  code_type_aux: 'code_type_aux'



# table_mapping : 
#     num_donneur : 'num_donneur_ordre'
#     reference_remise : 'reference_remise'
#     code_banque_receptrice : 'code_banque_receptrice'
#     date_emission : 'date_emission'
#     num_remise : 'num_remise'
#     ref_ben : 'ref_beneficiaire'
#     montant : 'montant'
#     date_execution : 'date_execution'
#     nom_donneur : 'nom_donneur_ordre'
#     nom_beneficiaire : 'nom_benificiaire'
#     rib_donneur : 'rib_donneur_ordre'
#     rib_beneficiaire : 'rib_beneficiaire'
#     motif_virement : 'motif_virement'
#     reference_virement : 'reference_virement'
#     reference_ben : 'reference_beneficiaire'
  