transformation_rules : 
    date_production : 
       type : date 
       form : '%Y%m%d'
    heure_production : 
       type : time
       form : '%H%M%S'
    date_emission : 
       type : date
       form : '%Y%m%d'
    montant : 
       type : int
       length : 16
       transformation : str("{0:.2f}".format(float(value)*100).zfill(length))
    date_execution :
       type : date 
       form : '%Y%m%d'
    nombre_total_virement : 
       type : int
       length : 5
       transformation : value.zfill(length)
    montant_total_virements :
       type : int 
       length : 20
       transformation : str(int(value)*100).zfill(length)
    